### ISSUE TITLE
Cannot add a column at the beginning

### ISSUE THREAD

**Issue by raffaem** [Kicamon/markdown-table-mode.nvim#6]
Take the following example:

```
| **Holiday n. 1** |            |
|------------------|------------|
| Start            | 2024-06-03 |
| End              | 2024-06-18 |
| Accounting       | 2024-06-25 |
```

Suppose I want to add a new column on the left of the first column.

I put the cursor on  the first line, press `0` to go to the first character, press `i` to insert on the  left of the cursor, press `|` for the new column separator.

The end result is that the  cursor is placed at the end of the line.

**Comment by Kicamon** [comment]
ok
